function AboutPage() {
  return (
    <div className="text-center p-10">
      <h1 className="text-2xl font-bold my-4">AboutPage</h1>
      <p className="text-gray-300">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem quod assumenda cupiditate nisi modi neque corporis obcaecati quas illo veniam sequi ab maxime ullam, odio illum facilis perspiciatis debitis enim doloremque dolor dolores, ut commodi. Repellat quaerat explicabo illo consequuntur dolor laboriosam aliquid blanditiis, incidunt iusto totam eaque deleniti tenetur officiis quam! Nostrum tempora eligendi maiores eius earum saepe. Quas exercitationem iure impedit quisquam, ad vero deserunt iusto repellendus esse aspernatur fuga sint cupiditate numquam fugiat! Sed dicta mollitia magnam enim amet rerum officia quod sunt maxime tempore, blanditiis tenetur atque officiis exercitationem odio! Expedita voluptates voluptas architecto quis mollitia, neque sed. Fugit cumque aperiam inventore quod voluptatum error atque non quia tenetur mollitia? At nihil numquam dolorem officia sit, voluptatem aliquam facilis modi, necessitatibus non labore, nulla magni facere! Odio praesentium quidem deleniti doloribus odit! Rem sapiente exercitationem praesentium odio nihil totam eum ex aut odit eligendi dolorem saepe quae, aliquid officiis cum ipsam optio nulla recusandae atque voluptate beatae. Voluptate quas sed velit. Neque, at? Enim pariatur eaque laboriosam delectus suscipit, eos facere, corrupti asperiores cupiditate voluptatem consequatur, aliquam fugit fugiat tempore commodi eius! A, ex. Praesentium, doloremque qui. Corporis qui ab, voluptates praesentium nam quod quia, eius minima nemo cum nesciunt quam expedita nostrum repudiandae. Mollitia voluptatum eaque laudantium officia ad voluptate dolorum perferendis sequi illum, quos excepturi rerum. Ea reiciendis eligendi aliquam pariatur esse quod nihil repellendus placeat suscipit molestias? Repudiandae laudantium nulla voluptatum, tempore error dolor. Voluptatum tenetur cupiditate cumque perspiciatis ipsa dolores veritatis? Delectus, praesentium adipisci explicabo incidunt magnam officiis magni voluptatum consequatur laudantium ullam at? Nemo ex suscipit et, voluptatibus illum autem repellat expedita alias beatae repellendus aut hic? Placeat optio quae culpa animi, beatae possimus aliquam dignissimos, laborum illum praesentium quos deleniti a sapiente in quasi natus assumenda ipsum rerum veniam? At?</p>
    </div>
  )
}

export default AboutPage
